export { PipesModule } from './pipes.module';
export { CallCenterAgentDisplayPipe } from './call-center-agent-display.pipe';
export { CommunityDisplayPipe } from './community-display.pipe';
export { FilterPipe } from './filter.pipe';
export { HeaderChunkPipe } from './header-chunk.pipe';
export { MomentCalendarFormatPipe } from './moment-calendar-format.pipe';
export { MomentFormatPipe } from './moment-format.pipe';
export { MomentFromNowFormatPipe } from './moment-from-now-format.pipe';
export { MomentHumanizeDurationFormatPipe } from './moment-humanize-duration-format.pipe';
export { PhoneNumberPipe } from './phone-number.pipe';
// export {  } from './safe-html.pipe';
export { SubstringPipe } from './substring.pipe';
export { SumPipe } from './sum.pipe';
export { TelephonePipe } from './telephone.pipe';
export { TextingFormatPipe } from './texting-format.pipe';
// export { UtcToLocalPipe } from './utc-to-local.pipe';
